version: "3.9"

services:
  npb_webhook:
    image: north_pole_buddy
    build:
      context: .
      dockerfile: Dockerfile
      target: "nolambda"
    command: "uvicorn npb.app:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/var/task/
