version: "3.9"

services:
  npb:
    image: npb
    build:
      context: .
      dockerfile: Dockerfile
      target: "dev"
    environment:
      - OPENAI_API_KEY=
      - TELEGRAM_BOT_TOKEN=dummy
      - TELEGRAM_SECRET_TOKEN=test
    volumes:
      - .:/var/task/
  npb_dev:
    extends:
      service: npb
    command: "uvicorn npb.app:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    env_file:
      - .env
  
